version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: vcomics_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    env_file:
      - ./apps/api/.env

  postgres:
    image: postgres:14
    container_name: vcomics_db
    env_file:
      - ./apps/api/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
  redis_data:
